### Invalid Staff Login
POST http://localhost:3001/api/login/staff
Content-Type: application/json

{
  "email": "staff@example.com",
  "password": "password123"
}

### Valid Staff Login
POST http://localhost:3001/api/login/staff
Content-Type: application/json

{
  "email": "maya.rivera@school.edu",
  "password": "AdminPass1!"
}