### Invalid Student Login
POST http://localhost:3001/api/login/student
Content-Type: application/json

{
  "email": "student@example.com",
  "password": "password123"
}

### Valid Student Login
# @name studentLogin
POST http://localhost:3001/api/login/student
Content-Type: application/json

{
  "email": "alice.johnson@school.edu",
  "password": "Passw0rd!"
}

### Get My Info with invalid Token
GET http://localhost:3001/api/private/my-info
Authorization: Bearer {{this is an invalid token}}

### Get My Info with valid Token
GET http://localhost:3001/api/private/my-info
Authorization: Bearer {{studentLogin.response.body.token}}

### Change Phone Number with invalid Token
POST http://localhost:3001/api/private/my-info
Authorization: Bearer {{this is an invalid token}}
Content-Type: application/json

{
  "phone_number": "555-123-9000"
}

### Change Phone Number with valid Token
POST http://localhost:3001/api/private/my-info
Authorization: Bearer {{studentLogin.response.body.token}}
Content-Type: application/json

{
  "phone_number": "555-123-9000"
}
### Get list of available Courses
GET http://localhost:3001/api/private/student/courses
Authorization: Bearer {{studentLogin.response.body.token}}

### Signup for Course
POST http://localhost:3001/api/private/student/courses/CSCI-1001
Authorization: Bearer {{studentLogin.response.body.token}}
Content-Type: application/json

{
  "action" : "signup"
}

### Drop out of Course queue
POST http://localhost:3001/api/private/student/courses/CSCI-1001
Authorization: Bearer {{studentLogin.response.body.token}}
Content-Type: application/json

{
  "action" : "drop"
}
### Get My Cohorts
GET http://localhost:3001/api/private/student/cohorts
Authorization: Bearer {{studentLogin.response.body.token}}

### Get the details of a specific cohort the student is in
GET http://localhost:3001/api/private/student/cohorts/1
Authorization: Bearer {{studentLogin.response.body.token}}
### Get the details of a specific cohort the student is not in
GET http://localhost:3001/api/private/student/cohorts/3
Authorization: Bearer {{studentLogin.response.body.token}}
### Logout
POST http://localhost:3001/api/logout
Authorization: Bearer {{studentLogin.response.body.token}}